apiVersion: v1
kind: Service
metadata:
  name: "dicom-viewer-service"
  labels:
    {{- include "dicom-viewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "dicom-viewer.selectorLabels" . | nindent 4 }}
