apiVersion: v1
kind: Service
metadata:
  name: "dicom-server-service"
  labels:
    {{- include "dicom-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: https
  selector:
    {{- include "dicom-server.selectorLabels" . | nindent 4 }}
