apiVersion: v1
kind: Secret
metadata:
  name: tf-creds
type: Opaque
stringData:
  credentials: |        
    [default]
    aws_access_key_id={{ .Values.credentials.aws.key }}
    aws_secret_access_key={{ .Values.credentials.aws.secret }}
    {{- if .Values.credentials.aws.session_token }}
    aws_session_token={{ .Values.credentials.aws.session_token }}
    {{- end }}
    region=us-east-1
